const LOGIN_LOADING = "LOGIN_LOADING";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";
const GALLERY_LOADING = "GALLERY_LOADING";
const GALLERY_SUCCESS = "GALLERY_SUCCESS";
const GALLERY_ERROR = "GALLERY_ERROR";
const PICTURE_LOADING = "PICTURE_LOADING";
const PICTURE_SUCCESS = "PICTURE_SUCCESS";
const PICTURE_ERROR = "PICTURE_ERROR";
const REGENTOKEN_LOADING = "PICTURE_LOADING";
const REGENTOKEN_SUCCESS = "PICTURE_SUCCESS";
const REGENTOKEN_ERROR = "PICTURE_ERROR";
const NOTIFICATION_LOADING = "NOTIFICATION_LOADING"
const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
const NOTIFICATION_ERROR = "NOTIFICATION_ERROR"

const types = {
    LOGIN_LOADING,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    GALLERY_LOADING,
    GALLERY_SUCCESS,
    GALLERY_ERROR,    
    PICTURE_LOADING,
    PICTURE_SUCCESS,
    PICTURE_ERROR,
    REGENTOKEN_LOADING,
    REGENTOKEN_SUCCESS,
    REGENTOKEN_ERROR,
    NOTIFICATION_LOADING,
    NOTIFICATION_SUCCESS,
    NOTIFICATION_ERROR
};

export default types;
